#!/usr/bin/bash
home=`pwd`
select mode in "list database" "create data base" "connect to data base" "shell" "exit"
do
case $mode in 
"list database")
if [ -d ~/meyasql ] 
then
ls ~/meyasql
else 
mkdir ~/meyasql
ls ~/meyasql
fi
;; 
"create data base")
echo "please enter database name"
read databaseName
if [ ! -d ~/meyasql/$databaseName ] 
then
mkdir -p ~/meyasql/$databaseName
echo "database created"
else 
echo "database already exist"
fi
;;
"connect to data base")
. ./tableManager.sh
;;
"shell")
useingDb="false"
echo "enter the querey :"
read querey
while [[ $querey != "." ]]
do
set -f
. $home/shell $querey
set +f
read querey
done
cd $home
echo "bye :)"
;;
"exit")
exit
;;
esac
done
