#!/usr/bin/bash
select mode in "list database" "create data base" "connect to data base" "exit"
do
case $mode in 
"list database")
if [ -d ~/meyasql ] 
then
ls ~/meyasql
else 
mkdir ~/meyasql
ls ~/meyasql
fi
;;
"create data base")
echo "please enter database name"
read databaseName
if [ ! -d ~/meyasql/$databaseName ] 
then
mkdir -p ~/meyasql/$databaseName
echo "database created"
else 
echo "database already exist"
fi
;;
"connect to data base")
echo "please enter database name"
read databaseName
if [ -d ~/meyasql/$databaseName ] 
then
cd ~/meyasql/$databaseName



select operation in "List tables" "Create table"  "Insert" "Delete" "Select" "Exit"
do
case $operation in
"List tables")
if [ "$(ls -A ~/meyasql/$databaseName)" ]
then
ls ~/meyasql/$databaseName
else
echo "No tables found...!!!"
fi
;;
"Create table")
echo "Enter Table Name"
read tableName
if [ "$(ls -A ~/meyasql/$databaseName/$tableName)" ] 
then
echo "That table already exists .. !!!"
else 
mkdir ~/meyasql/$databaseName/$tableName
cd $tableName
touch $tableName.table
touch $tableName.md
fi
;;
"Insert")
;;
"Delete")
;;
"Select")
;;
"Exit")
break 1
esac
done




#echo "database connected"
else 
echo "data base doesnot exist"
fi
;;
"exit")
exit
;;
esac
done
