#!/usr/bin/bash


select operation in "List tables" "Create table"  "Insert" "Delete" "Select" "Exit"
do
case $operation in
"List tables")
if [ "$(ls -A ~/meyasql/$databaseName)" ]
then
ls ~/meyasql/$databaseName
else
echo "No tables found...!!!"
fi
;;
"Create table")
echo "Enter Table Name"
read tableName
if [ -f "~/meyasql/$databaseName/$tableName)" ] 
then
echo "That table already exists .. !!!"
else
touch ~/meyasql/$databaseName/$tableName
touch ~/meyasql/$databaseName/.$tableName
inputFlag="false"
. ./createColoumn.sh 
echo "The table created Successfully ... !!!"

fi
;;
"Insert")
#cd /home/yahya/BashScript/BashProject/meyasql
. ./insertTable.sh
;;
"Delete")
;;
"Select")
#cd /home/yahya/BashScript/BashProject/meyasql
. ./selectTable.sh
;;
"Exit")
#break 1
#cd /home/yahya/BashScript/BashProject/meyasql
. ./main
esac
done
else 
echo "data base doesnot exist"
fi
