#!/usr/bin/bash
echo "please enter database name"
read databaseName
if [ -d ~/meyasql/$databaseName ] 
then
cd ~/meyasql/$databaseName
echo "database connected"
select operation in "List tables" "Create table"  "Insert" "Delete" "Select" "Exit"
do
case $operation in
"List tables")
if [ "$(ls -A ~/meyasql/$databaseName)" ]
then
ls ~/meyasql/$databaseName
else
echo "No tables found...!!!"
fi
;;
"Create table")
echo "Enter Table Name"
read tableName
if [ -f "~/meyasql/$databaseName/$tableName)" ] 
then
echo "That table already exists .. !!!"
else 
mkdir ~/meyasql/$databaseName/$tableName
cd ~/meyasql/$databaseName/$tableName
touch $tableName
touch ".$tableName"
fi
;;
"Insert")
;;
"Delete")
;;
"Select")
;;
"Exit")
break 1
esac
done
else 
echo "data base doesnot exist"
fi
